### ISSUE TITLE
variable width, precision, etc

### ISSUE THREAD

**Issue by dhduvall** [CasualX/fmtools#3]
I couldn't find an example, and I couldn't make it work: is there a way to have, say, a width be defined by a variable, as described at https://doc.rust-lang.org/nightly/alloc/fmt/index.html#width? The macros here don't really take any arguments (that I can tell?), and it seems that neither `{variable:<width$}` nor `{variable:<w$,w=width}` doesn't work, so I'm not sure if this can be done. But it sure would be nice. 😃

**Comment by CasualX** [comment]
Hi, this feature is implemented but it isn't documented:

```rust
fn main() {
	let name = "World";
	let width = 8;
	fmtools::println!("Hello "{name, width:>1$}"!");
}
```

This prints Hello&nbsp;&nbsp;&nbsp;&nbsp;World!

Provide two arguments in the braces separated by a comma and it'll be appended to the underlying `format_args!` as an additional argument, then use `1` to refer to it (cannot be referred to by name).

It's not documented as I'm not sure how to explain this and it doesn't really follow std's convention.

**Comment by dhduvall** [comment]
Fantastic, thanks!
