### ISSUE TITLE
How to use with obfstr?

### ISSUE THREAD

**Issue by adamski** [CasualX/fmtools#5]
I'm trying to find documentation on how to use this in conjunction with obfstr to obfuscate formatted strings

**Comment by CasualX** [comment]
This is not documented publicly (intentionally as I think it's too much of a niche use case) but all you do is enable the `obfstr` feature when declaring fmtools as your dependency:

```text
[dependencies]
fmtools = { version = "0.1", features = ["obfstr"] }
```

That's all, now all the strings created with fmtools are obfuscated automatically.
